-- MySQL Script generated by MySQL Workbench
-- Tue Jun  3 22:14:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Hidroponia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Hidroponia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Hidroponia` DEFAULT CHARACTER SET utf8 ;
USE `Hidroponia` ;

-- -----------------------------------------------------
-- Table `Hidroponia`.`sistemas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hidroponia`.`sistemas` (
  `id_sistema` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `fecha_instalacion` DATE NULL,
  PRIMARY KEY (`id_sistema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hidroponico`.`sensores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hidroponia`.`sensores` (
  `id_sensores` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `tipo` VARCHAR(50) NULL,
  `pin_entrada` INT NULL,
  `id_sistema` INT NULL,
  PRIMARY KEY (`id_sensores`),
  INDEX `id_sistema_idx` (`id_sistema` ASC) VISIBLE,
  CONSTRAINT `id_sistema`
    FOREIGN KEY (`id_sistema`)
    REFERENCES `Hidroponia`.`sistemas` (`id_sistema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hidroponia`.`lecturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hidroponia`.`lecturas` (
  `id_lectura` INT NULL AUTO_INCREMENT,
  `id_sensor` INT NULL,
  `valor` FLOAT NULL,
  `fecha_hora` DATETIME NULL,
  PRIMARY KEY (`id_lectura`),
  INDEX `id_sensor_idx` (`id_sensor` ASC) VISIBLE,
  CONSTRAINT `id_sensor`
    FOREIGN KEY (`id_sensor`)
    REFERENCES `Hidroponia`.`sensores` (`id_sensores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hidroponia`.`actuadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hidroponia`.`actuadores` (
  `id_actuador` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `tipo` VARCHAR(50) NULL,
  `estado_actual` ENUM('ON', 'OFF') NULL DEFAULT 'OFF',
  `pin_salida` INT NULL,
  `id_sistema` INT NULL,
  PRIMARY KEY (`id_actuador`),
  INDEX `id_sistema_idx` (`id_sistema` ASC) VISIBLE,
  CONSTRAINT `ik_id_sistema`
    FOREIGN KEY (`id_sistema`)
    REFERENCES `Hidroponia`.`sistemas` (`id_sistema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hidroponia`.`eventos_control`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hidroponia`.`eventos_control` (
  `id_evento` INT NULL AUTO_INCREMENT,
  `id_actuador` INT NULL,
  `accion` ENUM('ON', 'OFF') NULL,
  `fecha_hora` DATETIME NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_evento`),
  INDEX `id_actuador_idx` (`id_actuador` ASC) VISIBLE,
  CONSTRAINT `ik_id_actuador`
    FOREIGN KEY (`id_actuador`)
    REFERENCES `Hidroponia`.`actuadores` (`id_actuador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hidroponia`.`umbrales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hidroponia`.`umbrales` (
  `id_umbrales` INT NULL AUTO_INCREMENT,
  `tipo_sensor` VARCHAR(50) NULL,
  `valor_min` FLOAT NULL,
  `valor_max` FLOAT NULL,
  `id_sistema` INT NULL,
  PRIMARY KEY (`id_umbrales`),
  INDEX `id_sistema_idx` (`id_sistema` ASC) VISIBLE,
  CONSTRAINT `ak_id_sistema`
    FOREIGN KEY (`id_sistema`)
    REFERENCES `Hidroponia`.`sistemas` (`id_sistema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
